

#hyprshell (windows management)
exec-once = hyprshell run &


#exec-once = hyprpaper
exec-once = dunst
#exec-once = edex-ui

exec-once = bongocat -c ./.config/bongocat/bongocat.conf 
exec-once = waybar

#pywal
exec-once = wal -R

# WAYPAPER
exec-once=waypaper --restore;

#computer graphics vsync

exec-once=MESA_VK_WSI_PRESENT_MODE=immediate
exec-once=MESA_NO_VSYNC=1

#quick-shell overview
exec-once = qs -c overview  

exec-once = bash -lc 'hyprctl output create headless VNC-1; sleep 0.2; hyprctl keyword monitor "VNC-1,1920x1080@60,auto,1"; wayvnc -o VNC-1 0.0.0.0 5900'
