# Execute your favorite apps at launch
exec-once = waybar
exec-once = hyprpaper
exec-once = dunst
#exec-once = edex-ui

# WAYPAPER
exec-once=waypaper --restore

# VNC
exec-once = bash -lc 'hyprctl output create headless VNC-1; sleep 0.2; hyprctl keyword monitor "VNC-1,1920x1080@60,auto,1"; wayvnc -o VNC-1 0.0.0.0 5900'
