

#hyprshell (windows management)
exec-once = hyprshell run &


#exec-once = hyprpaper
exec-once = dunst
#exec-once = edex-ui

#exec-once = bongocat -c ./.config/bongocat/bongocat.conf 
#exec-once = waybar


#pywal
#exec-once = wal -R

# WAYPAPER
#exec-once=waypaper --restore;

#computer graphics vsync

exec-once=MESA_VK_WSI_PRESENT_MODE=immediate
exec-once=MESA_NO_VSYNC=1

#QUICK-SHELL 
#overview
exec-once = qs -c overview
#noctalia
exec-once= qs -c noctalia-shell

