# ----------------------------------------------------- 
# Monitor Multiple
# name: "multiple"
# ----------------------------------------------------- 

monitor = DP-3 , 1920x1080@144, 0x0 ,1, transform, 1    #second 144hz

monitor = DP-2 , 3840x2160@60, 1080x0, 1.5   #main 4k

monitor = , 1920x1080, auto, 1, #tv
