# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e6e0e9"

# Title color for boxes
theme[title]="#d0bcff"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#ccc2dc"

# Background color of selected item in processes box
theme[selected_bg]="#d0bcff"

# Foreground color of selected item in processes box
theme[selected_fg]="#381e72"

# Color of inactive/disabled text
theme[inactive_fg]="#cac4cf"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#ccc2dc"

# Cpu box outline color
theme[cpu_box]="#948f99"

# Memory/disks box outline color
theme[mem_box]="#948f99"

# Net up/down box outline color
theme[net_box]="#948f99"

# Processes box outline color
theme[proc_box]="#948f99"

# Box divider line and small boxes line color
theme[div_line]="#49454e"

# Temperature graph colors
theme[temp_start]="#ccc2dc"
theme[temp_mid]="#d0bcff"
theme[temp_end]="#f2b8b5"

# CPU graph colors
theme[cpu_start]="#ccc2dc"
theme[cpu_mid]="#d0bcff"
theme[cpu_end]="#f2b8b5"

# Mem/Disk free meter
theme[free_start]="#ccc2dc"
theme[free_mid]=""
theme[free_end]="#2b292f"

# Mem/Disk cached meter
theme[cached_start]="#ccc2dc"
theme[cached_mid]=""
theme[cached_end]="#2b292f"

# Mem/Disk available meter
theme[available_start]="#d0bcff"
theme[available_mid]=""
theme[available_end]="#4f378b"

# Mem/Disk used meter
theme[used_start]="#f2b8b5"
theme[used_mid]=""
theme[used_end]="#8c1d18"

# Download graph colors
theme[download_start]="#ccc2dc"
theme[download_mid]="#d0bcff"
theme[download_end]="#ccc2dc"

# Upload graph colors
theme[upload_start]="#ccc2dc"
theme[upload_mid]="#d0bcff"
theme[upload_end]="#ccc2dc"